default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: quizzes_development

test:
  <<: *default
  database: quizzes_test

production:
  <<: *default
  database: quizzes_production
