defaults: &defaults
  host: <%= ENV.fetch('REDIS_HOST') %>
  port: <%= ENV.fetch('REDIS_PORT') %>
  password: <%= ENV.fetch('REDIS_PWD') %>
  db: <%= ENV.fetch('REDIS_DB') %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
