# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b33d17b9544b4e486be60b24e2d24f988d7d21721667e542da81a52131e259da29438fa23ef3a3e3aa31d16484559c41dfb478c52ca1c5401fce6bdbf57c064

test:
  secret_key_base: fc0347b64c423357ab37f024cfb38dda15de00d6cdaa85de2050ad3abfb345f493b36d9058db05415dd301ad6f397536a6c4aac5ed2395eb8b7e006f688270cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
